spring:
  config:
    import:
      - classpath:properties/jwt.yml
      - classpath:properties/security.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tiary;MODE=MYSQL
    username: sa

  sql:
    init:
      schema-locations: classpath*:database/schema.sql

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true