spring:
  config:
    import:
      - classpath:config/properties/jwt.yml
      - classpath:config/properties/security.yml
      - classpath:config/properties/aws.yml

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tiary;MODE=MYSQL
    username: sa

  sql:
    init:
      schema-locations: classpath*:database/schema.sql

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true