spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tiary;MODE=MYSQL
    username: sa

  sql:
    init:
      schema-locations: classpath*:database/schema.sql

  jpa:
    hibernate:
      ddl-auto: none