spring:
  config:
    import:
      - classpath:properties/database/common.yml
      - classpath:properties/database/h2.yml

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
