spring:
  config:
    import:
      - classpath:properties/jwt.yml
      - classpath:properties/security.yml
      - classpath:properties/aws.yml
      - classpath:properties/scheduler.yml

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tiary;MODE=MYSQL
    username: sa

  sql:
    init:
      schema-locations: classpath*:database/schema.sql

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587

    username: ${SPRING_MAIL_USERNAME:test@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:test}

    properties:
      mail:
        smtp:
          auth: true

          starttls:
            enable: true