name: Develop Branch

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  sonarcloud:
    name: SonarCloud
    uses: ./.github/workflows/sonarcloud.yml

  amazon-ecs:
    if: github.event_name == 'push'
    needs: sonarcloud

    name: Amazon ECS
    uses: ./.github/workflows/amazon-ecs.yml
    secrets:
      aws-access-key-id: ${{ secrets.DEVELOP_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.DEVELOP_AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.DEVELOP_AWS_REGION }}

      aws-ecr-repository: ${{ secrets.DEVELOP_AWS_ECR_REPOSITORY }}
      aws-ecr-image-tag: ${{ secrets.DEVELOP_AWS_ECR_IMAGE_TAG }}
      dockerfile: ${{ secrets.DEVELOP_DOCKERFILE }}

      aws-ecs-task-definition: ${{ secrets.DEVELOP_AWS_ECS_TASK_DEFINITION }}
      aws-ecs-container-name: ${{ secrets.DEVELOP_AWS_ECS_CONTAINER_NAME }}
      aws-ecs-service: ${{ secrets.DEVELOP_AWS_ECS_SERVICE }}
      aws-ecs-cluster: ${{ secrets.DEVELOP_AWS_ECS_CLUSTER }}