name: Feature Branch

on:
  push:
    branches:
      - feature-*

  pull_request:
    branches:
      - feature-*

jobs:
  sonarcloud:
    name: SonarCloud
    uses: ./.github/workflows/sonarcloud.yml