name: Main branch

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repository
        uses: actions/checkout@v4

      - name: Run SonarQube analysis
        uses: ./.github/actions/sonarqube
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
